services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "8089:8089"
    restart: on-failure:5
    env_file:
      - ./.env
    environment:
      - PYTHONPATH=/app
    depends_on:
      - pgvector

  pgvector:
    hostname: pgvector
    image: ankane/pgvector
    ports:
      - "5432:5432"
    restart: on-failure:5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./procurement/db/init.pgsql:/docker-entrypoint-initdb.d/init.sql

# docker run --name pgvector -p 5432:5432 --restart on-failure:5 -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=postgres -v ./procurement/db/init.pgsql:/docker-entrypoint-initdb.d/init.sql ankane/pgvector